# Generated by Django 6.1 on 2026-08-25 09:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('sender', models.CharField(help_text="e.g. 'IT Support <it-support@university.edu>'", max_length=255)),
                ('body', models.TextField()),
                ('is_phishing', models.BooleanField()),
                ('red_flags', models.JSONField(blank=True, default=list, help_text='Structured list of red flag explanations')),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marked_as_phishing', models.BooleanField()),
                ('is_correct', models.BooleanField(editable=False)),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phishing_attempts', to=settings.AUTH_USER_MODEL)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='phishing_sim.scenario')),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'is_correct'], name='phishing_si_user_id_482b97_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'scenario'), name='unique_user_scenario_attempt')],
            },
        ),
    ]
