# Generated by Django 6.1 on 2026-08-27 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0004_alter_lesson_order_alter_question_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='section',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
