# Generated by Django 6.1 on 2026-08-28 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0005_question_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(blank=True, help_text='Must exactly match a <h2> heading in the lesson content', max_length=200)),
                ('prompt', models.TextField(help_text='The reflection question shown to the student')),
                ('model_answer', models.TextField(help_text='Shown after the student reveals it')),
                ('order', models.PositiveIntegerField(default=0)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='open_questions', to='lessons.lesson')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
